name: MacOS

on:
   workflow_dispatch:

jobs:

   ios_build:
      name: Build iOS
      runs-on: macos-latest
      continue-on-error: false

      steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           submodules: true

      - name: install boost
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.69.0 https://github.com/boostorg/boost.git
          cd boost
          ./bootstrap.sh

      - name: boost headers
        run: |
          cd boost
          ./b2 headers
          cp b2 ..

      - name: user-config
        run: |
          echo "using darwin : ios : clang++ : <compileflags>-Wno-deprecated-declarations
          <compileflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          <compileflags>-mios-version-min=12
          <compileflags>\"-arch arm64\"
          <compileflags>-fobjc-abi-version=2
          <linkflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          <linkflags>-mios-version-min=12
          <linkflags>\"-arch arm64\"
          <linkflags>-fobjc-abi-version=2 ;" >>~/user-config.jam;

      - name: build library
        run: |
          BOOST_ROOT=boost ./b2 -l400 cxxstd=14 target-os=iphone crypto=built-in darwin-ios address-model=64 variant=release link=static
          ls -l
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: libtorrent
          # A file, directory or wildcard pattern that describes what to upload
          path: /Users/runner/work/libtorrent/libtorrent/bin
