name: MacOS

on:
   workflow_dispatch:

jobs:

   ios_build:
      name: Build iOS
      runs-on: macos-latest
      continue-on-error: false

      steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           submodules: true

      - name: install boost
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.64.0 https://github.com/boostorg/boost.git
          cd boost
          # ./bootstrap.sh --with-libraries=system,thread,date_time,regex,serialization 
          ./bootstrap.sh
          
      # - name: boost headers
      #   run: |
      #     cd boost
      #     ./b2 headers

      - name: user-config
        run: |
          cd boost
          echo "using darwin : ios : clang++ : <compileflags>-Wno-deprecated-declarations
          <compileflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          <compileflags>-mios-version-min=11
          <compileflags>\"-arch arm64\"
          <compileflags>-fobjc-abi-version=2
          <linkflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          <linkflags>-mios-version-min=11
          <linkflags>\"-arch arm64\"
          <linkflags>-fobjc-abi-version=2 ;" >>~/user-config.jam;

          # echo "using darwin : ios : clang++ : <compileflags>-Wno-deprecated-declarations
          # <compileflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          # <compileflags>-mios-version-min=11
          # <compileflags>\"-arch arm64\"
          # <compileflags>-fobjc-abi-version=2
          # <linkflags>\"-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk\"
          # <linkflags>-mios-version-min=11
          # <linkflags>\"-arch arm64\"
          # <linkflags>-fobjc-abi-version=2 ;" >>~/user-config.jam;

      - name: build library
        run: |
          cd boost
          ./b2 -j4 cxxflags="-std=c++11 -stdlib=libc++" target-os=iphone toolset=darwin architecture=arm address-model=64 binary-format=mach-o abi=aapcs link=static variant=release state
          ls -l
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: libtorrent
          # A file, directory or wildcard pattern that describes what to upload
          path: /Users/runner/work/libtorrent/libtorrent/boost/stage
          
