name: MacOS

on:
   workflow_dispatch:

jobs:

   ios_build:
      name: Build iOS
      runs-on: macos-latest
      continue-on-error: true

      steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           submodules: true

      - name: clone build script
        run: |
          cd ..
          mkdir -p ios/src
          mv ./libtorrent ios/src/
          git clone https://github.com/publicissapient-france/libtorrent-ios-resources.git
          mv libtorrent-ios-resources/build-script/* ios/
          cd ios/
          make
          rm -rf .build/
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: libtorrent
          # A file, directory or wildcard pattern that describes what to upload
          path: /Users/runner/work/libtorrent/ios/
          
